# name обязателен (иначе конфликт компоузов на сервере)
name: welding

services:
  web:
    image: nginx:alpine
    container_name: welding-web
    restart: unless-stopped
    ports:
      - "127.0.0.1:8074:80"
    volumes:
      - ../site:/usr/share/nginx/html:ro
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf:ro
