server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    charset utf-8;

    location / {
        try_files $uri $uri.html $uri/ =404;
        # сайт активно развивается — просим браузер перепроверять файлы
        add_header Cache-Control "no-cache";
    }
    location ~* \.(png|jpg|jpeg)$ {
        expires 1d;
        add_header Cache-Control "public";
    }
}
